name: next_toll_veloe
description: Flutter application related to the Veloe Mega Hack Challenge  

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  google_sign_in: ^4.1.1
  barcode_scan: ^1.0.0
  permission_handler: ^4.2.0+hotfix.3
  cached_network_image: ^2.0.0
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/google-plus.png
    - assets/images/scan.png
    - assets/images/arrowlogo.png
    - assets/images/sad.png
    - assets/images/lead.png
    - assets/images/sadface.png
